//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.Libraries.Yggdrasil.Assets {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.Libraries.Yggdrasil.Assets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LastAccess.
        /// </summary>
        internal static string ATT_APP_LAST_ACCESS {
            get {
                return ResourceManager.GetString("ATT_APP_LAST_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        internal static string ATT_APP_VERSION {
            get {
                return ResourceManager.GetString("ATT_APP_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a value.
        /// </summary>
        internal static string ATT_NAME_VALUE {
            get {
                return ResourceManager.GetString("ATT_NAME_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Index.
        /// </summary>
        internal static string CAP_INDEX {
            get {
                return ResourceManager.GetString("CAP_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nameless.
        /// </summary>
        internal static string CAP_NAMELESS {
            get {
                return ResourceManager.GetString("CAP_NAMELESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duplicate category &quot;{0}&quot;, category must be unique..
        /// </summary>
        internal static string ERR_CAT_DUPLICATED {
            get {
                return ResourceManager.GetString("ERR_CAT_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The category &quot;{0}&quot; does not exists on the configuration file..
        /// </summary>
        internal static string ERR_CAT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_CAT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found comparing two assemblies versions, the assemblies must had the same name..
        /// </summary>
        internal static string ERR_COMPARING_ASSEMBLY_VERSION {
            get {
                return ResourceManager.GetString("ERR_COMPARING_ASSEMBLY_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found creating the file &quot;{0}&quot;..
        /// </summary>
        internal static string ERR_CREATING_FILE {
            get {
                return ResourceManager.GetString("ERR_CREATING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found decrypting the string..
        /// </summary>
        internal static string ERR_DECRYPTING_STR {
            get {
                return ResourceManager.GetString("ERR_DECRYPTING_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The directory &quot;{0}&quot; does not exists..
        /// </summary>
        internal static string ERR_DIR_MISSING {
            get {
                return ResourceManager.GetString("ERR_DIR_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found adding downloading the file &quot;{0}&quot;..
        /// </summary>
        internal static string ERR_DOWNLOADING {
            get {
                return ResourceManager.GetString("ERR_DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found encrypting the string..
        /// </summary>
        internal static string ERR_ENCRYPTING_STR {
            get {
                return ResourceManager.GetString("ERR_ENCRYPTING_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found encrypting or decrypting the string, can&apos;t use encryption with an empty string..
        /// </summary>
        internal static string ERR_ENCRYPTION_EMPTY_STR {
            get {
                return ResourceManager.GetString("ERR_ENCRYPTION_EMPTY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file &quot;{0}&quot; not exists..
        /// </summary>
        internal static string ERR_FILE_MISSING {
            get {
                return ResourceManager.GetString("ERR_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error initializing the Medaka configuration file..
        /// </summary>
        internal static string ERR_INIT_MEDAKA {
            get {
                return ResourceManager.GetString("ERR_INIT_MEDAKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The XElement can not be added because its key is already part of the XCollection..
        /// </summary>
        internal static string ERR_KEY_ALREADY_IN_XML_COLL {
            get {
                return ResourceManager.GetString("ERR_KEY_ALREADY_IN_XML_COLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duplicate property &quot;{0}&quot;, property must be unique..
        /// </summary>
        internal static string ERR_PROP_DUPLICATED {
            get {
                return ResourceManager.GetString("ERR_PROP_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property &quot;{0}&quot; couldn&apos;t be found on the category &quot;{1}&quot;..
        /// </summary>
        internal static string ERR_PROPERTY_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_PROPERTY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found saving the file &quot;{0}&quot;..
        /// </summary>
        internal static string ERR_SAVING_FILE {
            get {
                return ResourceManager.GetString("ERR_SAVING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found scanning the &quot;{0}&quot;..
        /// </summary>
        internal static string ERR_SCANNING {
            get {
                return ResourceManager.GetString("ERR_SCANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found accessing the children by its index. The index &quot;{0}&quot; is out of bounds..
        /// </summary>
        internal static string ERR_XML_CHILDREN_INDEX_OUT_OF_BOUNDS {
            get {
                return ResourceManager.GetString("ERR_XML_CHILDREN_INDEX_OUT_OF_BOUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found adding the attribute &quot;{0}&quot; at node &quot;{0}&quot;. Attributes mus be unique..
        /// </summary>
        internal static string ERR_XML_DUPLICATED_ATT {
            get {
                return ResourceManager.GetString("ERR_XML_DUPLICATED_ATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred exporting the xml file..
        /// </summary>
        internal static string ERR_XML_EXPORTING {
            get {
                return ResourceManager.GetString("ERR_XML_EXPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The xml does not have the attribute &quot;{0}&quot;..
        /// </summary>
        internal static string ERR_XML_MISSING_ATTRIBUTE {
            get {
                return ResourceManager.GetString("ERR_XML_MISSING_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The xml does not have the node &quot;{0}&quot;..
        /// </summary>
        internal static string ERR_XML_MISSING_NODE {
            get {
                return ResourceManager.GetString("ERR_XML_MISSING_NODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error was found, xml node names must be unique..
        /// </summary>
        internal static string ERR_XML_NODE_NOT_UNIQUE {
            get {
                return ResourceManager.GetString("ERR_XML_NODE_NOT_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles: {0}:
        ///.
        /// </summary>
        internal static string STR_FORMAT_LAIN_ENTRY {
            get {
                return ResourceManager.GetString("STR_FORMAT_LAIN_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} : Count: {1}.
        /// </summary>
        internal static string STR_FORMAT_XLIST {
            get {
                return ResourceManager.GetString("STR_FORMAT_XLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a config.medaka.
        /// </summary>
        internal static string STR_MEDAKA_FILE {
            get {
                return ResourceManager.GetString("STR_MEDAKA_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assembly: {0}.dll
        ///Version: {1}
        ///Namespace: {2}
        ///Class: {3}
        ///Compile Date: {4}
        ///Copyright  {7}©
        ///Develope by {5} in {6}.
        /// </summary>
        internal static string STR_NAMELESS_DATA {
            get {
                return ResourceManager.GetString("STR_NAMELESS_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Api_Version.
        /// </summary>
        internal static string STR_PROPERTY_API_VERSION {
            get {
                return ResourceManager.GetString("STR_PROPERTY_API_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        internal static string STR_PROPERTY_COMPANY {
            get {
                return ResourceManager.GetString("STR_PROPERTY_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developer.
        /// </summary>
        internal static string STR_PROPERTY_DEVELOPER {
            get {
                return ResourceManager.GetString("STR_PROPERTY_DEVELOPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CompileDate.
        /// </summary>
        internal static string STR_PROPERTY_LAST_COMPILE_DATE {
            get {
                return ResourceManager.GetString("STR_PROPERTY_LAST_COMPILE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} : ({1}).
        /// </summary>
        internal static string STR_XCOLLECTION {
            get {
                return ResourceManager.GetString("STR_XCOLLECTION", resourceCulture);
            }
        }
    }
}
